### ISSUE TITLE
Starting as part of application supervision tree fails

### ISSUE THREAD

**Issue by tonnenpinguin** [commanded/commanded-ecto-projections#43]
Hey guys :) 

I was following along [this blog series](https://blog.nootch.net/post/event-sourcing-with-elixir-part-3/) but I'm stuck trying to add a Projector to the application's supervision tree.

It seems like commanded tries to read the configuration from the configured `application`. However, this one is not started yet when the supervision tree is initially built, causing the startup process to fail with the following error message 

```
** (Mix) Could not start application bank_api: BankAPI.Application.start(:normal, []) returned an error: shutdown: failed to start child: BankAPI.Accounts.Supervisor
    ** (EXIT) shutdown: failed to start child: :account_opened
        ** (EXIT) an exception was raised:
            ** (RuntimeError) could not lookup :bank_api because it was not started or it does not exist
                (commanded 1.3.1) lib/commanded/application/config.ex:45: Commanded.Application.Config.lookup/1
                (commanded 1.3.1) lib/commanded/application/config.ex:15: Commanded.Application.Config.get/2
                (commanded 1.3.1) lib/commanded/registration.ex:20: Commanded.Registration.start_link/5
                (commanded 1.3.1) lib/commanded/event/handler.ex:636: Commanded.Event.Handler.start_link/4
                (stdlib 3.15.2) supervisor.erl:414: :supervisor.do_start_child_i/3
                (stdlib 3.15.2) supervisor.erl:400: :supervisor.do_start_child/2
                (stdlib 3.15.2) supervisor.erl:384: anonymous fn/3 in :supervisor.start_children/2
                (stdlib 3.15.2) supervisor.erl:1234: :supervisor.children_map/4
                (stdlib 3.15.2) supervisor.erl:350: :supervisor.init_children/2
                (stdlib 3.15.2) gen_server.erl:423: :gen_server.init_it/2
                (stdlib 3.15.2) gen_server.erl:390: :gen_server.init_it/6
                (stdlib 3.15.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```

Is there a solution to this other than to send my supervisor an event to dynamically start the projector after the main application has started?

I uploaded my current state [here](https://github.com/tonnenpinguin/bank_api/tree/98a267a1dac028cd8a819aeea1e4b0905274c879)

Thank you in advance :)

**Comment by tonnenpinguin** [comment]
Nevermind, I'm an idiot. 

I went back through the commanded docs and fixed the setup (the blog is quite outdated). [This commit](https://github.com/tonnenpinguin/bank_api/commit/4c228f1e306c44396a1c5f19a9ec8b68ce88d721) does the trick.
