### ISSUE TITLE
`schema_versions` of app repo and event store colliding?

### ISSUE THREAD

**Issue by ShawnMcCool** [commanded/commanded-ecto-projections#55]
Is it necessary to configure these ecto projections and the commanded event store as different databases? They seem to have conflicting requirements for `schema_versions`.

```elixir
❯ mix ecto.create
The database for Game.Repo has been created
❯ mix ecto.migrate

22:17:18.510 [info] == Running 20241201194924 CreateProjectionVersions.change/0 forward

22:17:18.511 [info] create table projection_versions

22:17:18.520 [info] == Migrated 20241201194924 in 0.0s

22:17:18.547 [info] == Running 20241201195935 CreateBuilderDungeonsProjection.change/0 forward

22:17:18.547 [info] create table builder_dungeons_projection

22:17:18.551 [info] == Migrated 20241201195935 in 0.0s
❯ mix ecto.migrate

22:17:28.173 [info] Migrations already up
❯ mix do event_store.create, event_store.init
The EventStore database already exists.
The EventStore schema already exists.
** (Postgrex.Error) ERROR 42P07 (duplicate_table) relation "schema_migrations" already exists
    (postgrex 0.19.3) lib/postgrex.ex:355: Postgrex.query!/4
    (elixir 1.17.2) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    (db_connection 2.7.0) lib/db_connection.ex:1756: DBConnection.run_transaction/4
    (eventstore 1.4.6) lib/event_store/tasks/init.ex:47: EventStore.Tasks.Init.exec/2
    (elixir 1.17.2) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
    (eventstore 1.4.6) lib/mix/tasks/event_store.init.ex:45: Mix.Tasks.EventStore.Init.run/1
    (mix 1.17.2) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
    (elixir 1.17.2) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
```

**Comment by ShawnMcCool** [comment]
I'm realizing it's an event store issue not a projection issue. Sorry, it's late.
